name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all-features
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v2
    - name: Verify autoformatter
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v2
    - name: Verify linter
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-features -- -D warnings
